In [6]:
import numpy as np 

arr_1 = np.array([[1, 2],[3, 4]])
#Chuyển vị sử dụng hàm np.transpose
arr_transposed_1 = np.transpose(arr_1)
#Sử dụng toán tử T
arr_transposed_2 = arr_1.T

#In ra màn hình
print("array 1: \n",arr_1)
print("sau khi chuyển bị bằng np.transpose: \n",arr_transposed_1)
print("Sau khi dùng toán tử T: \n",arr_transposed_2)

array 1: 
 [[1 2]
 [3 4]]
sau khi chuyển bị bằng np.transpose: 
 [[1 3]
 [2 4]]
Sau khi dùng toán tử T: 
 [[1 3]
 [2 4]]


Using famework pytorch for transposed matrix

In [10]:
import torch

tensor_1 = torch.tensor([[1, 2], [3, 4]])
#Chuyển vị tensor
#Chuyển vị bằng hàm torch.t()
tensor_transpose_1 = torch.t(tensor_1)
#Chuyển vị bằng hàm torch.transpose
tensor_transpose_2 = torch.transpose(tensor_1, 0, 1)

#in ra màn hình
print("tensor 1: \n",tensor_1)
print("Chuyển vị bằng hàm torch.t: \n",tensor_transpose_1)
print("Chuyển vị bằng hàm torch.transpose: \n",tensor_transpose_2)

tensor 1: 
 tensor([[1, 2],
        [3, 4]])
Chuyển vị bằng hàm torch.t: 
 tensor([[1, 3],
        [2, 4]])
Chuyển vị bằng hàm torch.transpose: 
 tensor([[1, 3],
        [2, 4]])


Using tensorflow for transposed : tf.transpose()

In [12]:
import tensorflow as tf

#tạo tensor 2d
tensor_1_tf = tf.constant([[1,2],[3, 4]])
#Chuyển vị tensor
tensor_transpose_tf = tf.transpose(tensor_1_tf)

#In ra màn hình
print("Chuyển vị bằng tensoflow: \n",tensor_transpose_tf)

Chuyển vị bằng tensoflow: 
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


Using Summation

Using numpy for summation

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_sum = np.sum(arr_1)

#Compute for columm : np.sum(arr,axis = 0)
columm_sum = np.sum(arr, axis = 0)

#Compute for row: np.sum(arr, asix=1)
row_sum = np.sum(arr, axis=1)

# In ra màn hình
print("Tính tổng tất cả phần tử trong mảng: \n",total_sum)
print("Tính theo cột: \n",columm_sum)
print("Tính theo hàng: \n",row_sum)

Tính tổng tất cả phần tử trong mảng: 
 10
Tính theo cột: 
 [5 7 9]
Tính theo hàng: 
 [ 6 15]


Using Pytorch for Summation

In [22]:
tensor_1 = torch.tensor([[1, 2],[3, 4]])

# Tính tổng  các phần tử trong mảng:
total_sum = torch.sum(tensor_1)

#Tính tổng tensor theo cột
columm_tensor_sum = torch.sum(tensor_1, axis = 0)

#Tính tổng tensor theo hàng

row_tensor_sum = torch.sum(tensor_1, axis = 1)

#In ra màn hình
print("Tensor: \n",tensor_1)
print("Tính tổng các phần tử trong tensor: \n",total_sum)
print("Tính tổng tensor theo cột: \n", columm_tensor_sum)
print("Tính tổng tensor theo hàng: \n",row_tensor_sum)


Tensor: 
 tensor([[1, 2],
        [3, 4]])
Tính tổng các phần tử trong tensor: 
 tensor(10)
Tính tổng tensor theo cột: 
 tensor([4, 6])
Tính tổng tensor theo hàng: 
 tensor([3, 7])


Using tensorflow for Summation



In [23]:
tensor_1_tf = tf.constant([[1, 2],[3, 4]])

#Tính tổng tensor
total_sum = tf.reduce_sum(tensor_1_tf)

#Tính tổng tensor theo cột
columm_tf_sum = tf.reduce_sum(tensor_1_tf, axis=0)

#Tính tổng tensor theo hàng
row_tf_sum = tf.reduce_sum(tensor_1_tf)

#In ra màn hình
print("Tensor: \n",tensor_1_tf)
print("Tổng các phần tử trong tensor: \n",total_sum)
print("Tính tổng tensor theo cột: \n",columm_tf_sum)
print("Tính tổng tensor theo hàng: \n",row_tensor_sum)

Tensor: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tổng các phần tử trong tensor: 
 tf.Tensor(10, shape=(), dtype=int32)
Tính tổng tensor theo cột: 
 tf.Tensor([4 6], shape=(2,), dtype=int32)
Tính tổng tensor theo hàng: 
 tensor([3, 7])


Using Numpy

In [40]:
import random
random.seed(2024)
arr_1 = np.random.randint(-10, 10, size = (3,4))
arr_2 = np.transpose(arr_1) 
print(arr_1)
print(arr_2)
arr_mul = np.dot(arr_1,arr_2)
print(arr_mul)

[[-2  9  0  7]
 [-8  7  0 -6]
 [-5  4  1  6]]
[[-2 -8 -5]
 [ 9  7  4]
 [ 0  0  1]
 [ 7 -6  6]]
[[134  37  88]
 [ 37 149  32]
 [ 88  32  78]]


Using Pytorch

In [276]:
import random

arr_1 = torch.rand(3, 4) *20 - 10
arr_2 = torch.transpose(arr_1, dim0=0, dim1=1 ) 
print(arr_1)
print(arr_2)
arr_mul = torch.matmul(arr_1,arr_2) # nhân ma trận using pytorch
print(arr_mul)

tensor([[ 6.4490,  9.7831,  6.5770,  5.1935],
        [-7.1981,  4.3562, -1.5948,  5.0646],
        [ 5.4584,  9.7957, -5.3483, -6.0102]])
tensor([[ 6.4490, -7.1981,  5.4584],
        [ 9.7831,  4.3562,  9.7957],
        [ 6.5770, -1.5948, -5.3483],
        [ 5.1935,  5.0646, -6.0102]])
tensor([[207.5289,  12.0104,  64.6436],
        [ 12.0104,  98.9823, -18.5274],
        [ 64.6436, -18.5274, 190.4762]])


Using Tensorflow

In [66]:
import random
random.seed(2024)
rows = 3
cols = 4
arr_1 = tf.random.uniform((rows, cols),minval=-10,maxval=10)
arr_2 = tf.transpose(arr_1) 
print(arr_1)
print(arr_2)
arr_mul = tf.matmul(arr_1,arr_2) # nhân ma trận using pytorch
print(arr_mul)

tf.Tensor(
[[ 0.92443943 -0.09798241  5.672674    6.155098  ]
 [-0.9014988  -1.8432541   7.324583    5.4655743 ]
 [-6.704762    2.3129463  -8.0647135   4.8157387 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 0.92443943 -0.9014988  -6.704762  ]
 [-0.09798241 -1.8432541   2.3129463 ]
 [ 5.672674    7.324583   -8.0647135 ]
 [ 6.155098    5.4655743   4.8157387 ]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[ 70.92865   74.538345 -22.531925]
 [ 74.538345  87.7323   -30.968899]
 [-22.531925 -30.968899 138.5345  ]], shape=(3, 3), dtype=float32)


Excercise 2:

Using Numpy

In [266]:
random.seed = 2024
arr = np.random.randint(-10,10, size=(3, 3))
print(arr)
arr_1 = np.sum(arr)
arr_col_sum = np.sum(arr, axis=0)
print(arr_col_sum)
arr_row_sum = np.sum(arr, axis=1)
print(arr_row_sum)

[[-5  2  3]
 [-6  3  5]
 [ 9 -1  5]]
[-2  4 13]
[ 0  2 13]


Using Pytorch


In [269]:
tensor_1 = torch.rand(3,3)* 20 - 10
print(tensor_1)
tensor_sum = torch.sum(tensor_1)
print("Tensor: \n",tensor_sum)
tensor_col_sum = torch.sum(tensor_1, axis=0)
print("Sum tensor axis = 0: \n",tensor_col_sum)
tensor_row_sum = torch.sum(tensor_1, axis=1)
print("Sum tensor axis = 1: \n",tensor_row_sum)

tensor([[ 3.5401,  9.5630, -0.2570],
        [ 4.5721,  7.8477,  3.8390],
        [-5.5898,  4.1033,  8.0840]])
Tensor: 
 tensor(35.7025)
Sum tensor axis = 0: 
 tensor([ 2.5224, 21.5141, 11.6661])
Sum tensor axis = 1: 
 tensor([12.8461, 16.2588,  6.5976])


Using Tensorflow

In [193]:
tensor_tf = tf.random.uniform((3, 3),-10,10)
print(tensor_tf)
tensor_tf_sum = tf.reduce_sum(tensor_tf)
print(tensor_tf_sum)
tensor_tf_col = tf.reduce_sum(tensor_tf, axis=0)
print(tensor_tf_col)
tensor_tf_row = tf.reduce_sum(tensor_tf, axis=1)
print(tensor_tf_row)

tf.Tensor(
[[ 4.594717   4.8401546 -1.9022827]
 [-5.09789    9.409943   4.558485 ]
 [-7.755511   1.5555811 -4.9947715]], shape=(3, 3), dtype=float32)
tf.Tensor(5.208426, shape=(), dtype=float32)
tf.Tensor([-8.258684  15.805678  -2.3385692], shape=(3,), dtype=float32)
tf.Tensor([  7.532589   8.870538 -11.194701], shape=(3,), dtype=float32)
