In [4]:
import numpy as np
 
#numpy to create array zero

arr_numpy = np.zeros((3, 3))
print(arr_numpy)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#tensorflow to create array zero
import tensorflow as tf
arr_tf = tf.zeros((3, 3))
print(arr_tf)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [7]:
#pytorch to create array zeros
import torch

tensor_zeros = torch.zeros((3, 3))
print(tensor_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# numpy to create array ones , np.ones

arr_ones = np.ones((3, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# tensorflow to create array ones , tf.ones
tf_ones = tf.ones((3, 4))
print(tf_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [15]:
#pytorch to create tensor_ones 
tensor_ones = torch.ones((3, 4))
print(tensor_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
# numpy to create arr.full
arr_fill = np.full((3, 4), 5)
print(arr_fill)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
#tensorflow to create tf_fill
tf_fill = tf.fill((3, 4), 5)
print(tf_fill)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [22]:
#pytorch to create tensor_full
tensor_full = torch.full((3, 4), 5)
print(tensor_full)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
