In [1]:
import numpy as np
import torch
import tensorflow as tf

In [6]:
list_data = [1,2,3,4,5,6,7,8,9,10]

list_numpy = np.array(list_data)
print("Array Numpy:\n ",list_numpy,type(list_numpy))

Array Numpy:
  [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [11]:
#pytorch tensor
tensor_1D_pt = torch.tensor(list_data)
print(tensor_1D_pt)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [17]:
#tensorflow
tensor_1D_tf = tf.convert_to_tensor(list_data) #1
print(tensor_1D_tf)
tensor_1D_tf_cst = tf.constant(list_data) #2                        #1 == #2
print(tensor_1D_tf_cst)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


Create 2D array == numpy,pytorch,tensorflow

In [2]:
list_2D = [[1,2,3],
           [3,4,5],
           [6,7,8]]

In [5]:
#using numpy
arr_2D = np.array(list_2D)
print(arr_2D)
print("Hinh dang mang", arr_2D.shape)
print("Kieu du lieu mang", arr_2D.dtype)
print("Loai cua mang", type(arr_2D))


[[1 2 3]
 [3 4 5]
 [6 7 8]]
Hinh dang mang (3, 3)
Kieu du lieu mang int64
Loai cua mang <class 'numpy.ndarray'>


In [3]:
#using pytorch
arr_2D_pt = torch.tensor(list_2D)
print(arr_2D_pt)
print("Hinh dang mang", arr_2D_pt.shape)
print("Kieu du lieu mang",arr_2D_pt.dtype)
print("Loai cua mang", type(arr_2D_pt))
print("Thiet bi ma tensor luu tru",arr_2D_pt.device)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])
Hinh dang mang torch.Size([3, 3])
Kieu du lieu mang torch.int64
Loai cua mang <class 'torch.Tensor'>
Thiet bi ma tensor luu tru cpu


In [6]:
#using tensorflow
arr_2D_tf = tf.convert_to_tensor(arr_2D)
print(arr_2D_tf)
print("Hinh dang mang", arr_2D_tf.shape)
print("Kieu du lieu mang",arr_2D_tf.dtype)
print("Loai cua mang", type(arr_2D_tf))
print("Thiet bi ma tensor luu tru",arr_2D_tf.device)

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int64)
Hinh dang mang (3, 3)
Kieu du lieu mang <dtype: 'int64'>
Loai cua mang <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiet bi ma tensor luu tru /job:localhost/replica:0/task:0/device:GPU:0
